### ISSUE TITLE
[Token Login] Just logging me out

### ISSUE THREAD

**Issue by Xenorio** [Cr3atable/Discord-plugins#1]
When i paste a token (Bot token) an click login, it just loads for a second and then i'm getting the default Discord login screen.

OS: Ubuntu 18.04
ED, Discord, and the plugin are all up to date

**Comment by JustJerBE** [comment]
Same problem on Windows 10!

**Comment by Cr3atable** [comment]
Oh hey, GitHub did not notify me of this. Token login is not made for Bot tokens, it's made for user tokens (it's easier to have a text file with login tokens if you have alts, that's why I made this). Not even sure it works with the bot login plugin.
